version: '3.7'

services:

  articles:
    image: radax00/articles:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - micro-service-network-2

  # client angular with primeng application that consumes microservices through a gateway (http://localhost:4200)
  product-cli:
    image: radax00/product-cli:latest
    ports:
      - "4200:80/tcp"
    networks:
      - micro-service-network-2
    environment:
      API_URL: "http://localhost:8765/"
    links:
      - articles
networks:
  micro-service-network-2:
